language: node_js
node_js:
 - "0.10"
env:
  - NODE_ENV=test DB_NAME=benefisher_test DB_USERNAME=root DB_HOST=127.0.0.1 API_URL=http://wakati-ohana-api.herokuapp.com
before_install:
  - npm update -q
  - npm install grunt-cli -g
install: npm install
before_script:
  - grunt build
  - mysql -e 'create database benefisher_test;'
notifications:
  slack: wakati:3iYgzXNQmlXRUmfl702XqQ5Q""