# Site settings
title: Benefisher
email: hello@codeforsacramento.org
description: > # this means to ignore newlines until "baseurl:"
  Benefisher!! The most awesome website ever!!
baseurl: "/benefisher"
url: "https://wakati.github.io"
members:
  Team Wakati: wakati
  Adrian : Terrell707
  Anthony : Anthoknee
  James : mrjamesdoan
  Daniel : dangr1
  Jesse : jesserosato

# Build settings
markdown: kramdown
