# Site settings
title: Benefisher
email: hello@codeforsacramento.org
description: > # this means to ignore newlines until "baseurl:"
  Benefisher is a social services search application built to more
  easily connect those in need with those that can help.
baseurl: "/benefisher"
url: "https://wakati.github.io"
members:
  Adrian : Terrell707
  Anthony : Anthoknee
  James : mrjamesdoan
  Daniel : dangr1
  Jesse : jesserosato

# Build settings
markdown: kramdown
