# Site settings
title: Benefisher
email: hello@codeforsacramento.org
description: > # this means to ignore newlines until "baseurl:"
  Benefisher!! The most awesome website ever!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
members:
  Team Wakati: wakati
  Adrian : Terrell707
  Anthony : Anthoknee
  James : mrjamesdoan
  Daniel : dangr1
  Jesse : jesserosato

# Build settings
markdown: kramdown
